title: Offsec Blog
description: Things that excite me | Things that I dont want to forget.
show_downloads: false
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

github:
  zip_url: https://github.com/kyle41111/kyle41111.github.io
  another_url: https://github.com/kyle41111
